# -*- coding: utf-8 -*-
"""
    This file is execfile()d with the current directory set to its
    containing dir.

    Note that not all possible configuration values are present in this
    autogenerated file.

    All configuration values have a default; values that are commented out
    serve to show the default.

    If extensions (or modules to document with autodoc) are in another directory,
    add these directories to sys.path here. If the directory is relative to the
    documentation root, use os.path.abspath to make it absolute, like shown here.
"""

import os
import sys
sys.path.insert(0, os.path.abspath(".."))
import bagels_theme

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = "1.0"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named "sphinx.ext.*") or your custom
# ones.
extensions = ["sphinx.ext.autodoc",
              "sphinx.ext.doctest",
              "sphinx.ext.intersphinx",
              "sphinx.ext.todo",
              "sphinx.ext.coverage",
              "sphinx.ext.imgmath",
              "sphinx.ext.ifconfig",
              "sphinx.ext.viewcode"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = [".rst", ".md"]
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Bagels Theme"
copyright = "2018, Bryant Biggs"
author = "Bryant Biggs"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = bagels_theme.__version__
# The full version, including alpha/beta/rc tags.
release = bagels_theme.__version__


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme_path = bagels_theme.get_html_theme_path()

html_theme = "bagels_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    # "github_user": "bryantbiggs",
    # "github_repo": "bagels_theme",
    # "github_button": "true",
    # "github_banner": "true",
    # "sidebar_collapse": "true",
    # "show_related": "true",
    # "page_width": "1100px",
    # "font_family": "Roboto Slab, serif",
    # "font_size": "16px",
    # "head_font_family": "Lato, sans-serif",
    # "code_font_family": "Roboto Mono, monospace",
    # "code_font_size": "0.9em",
    # "footer_text": "#FD8B25",
    # "footnote_bg": "#FEE7D3",
    # "footnote_border": "#FEE7D3"
}

html_title = "Bagels Theme Demo"

# A shorter title for the navigation bar.  Default is the same as html_title.

# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.

# html_logo = "_static/logo.jpg"

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.

# html_favicon = "_static/favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# -- Options for code output -------------------------------------------

# Don"t show full chain path, just function
add_module_names = False
